# Generated by Django 4.0.3 on 2022-03-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование подкатегории')),
                ('study_time', models.IntegerField(verbose_name='Время изучения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study_plan.category', verbose_name='Подкатегория')),
            ],
        ),
    ]
