# Generated by Django 4.0.3 on 2022-03-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('planned_to_study', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('last_study', models.DateTimeField(auto_now=True, verbose_name='Последнее изучение')),
                ('study_time', models.IntegerField(verbose_name='Время изучения')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('studied', models.BooleanField(default=True, verbose_name='Изучено?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study_plan.subcategory', verbose_name='Подкатегория')),
            ],
        ),
    ]
